<?php
function d_enqueue() {
  wp_register_style(
    'd_front-rubik_and_pacifico',
    'https://fonts.googleapis.com/css2?family=Pacifico&family=Rubik:wght@300;400;500;700&display=swap',
    [],
    null
  );
  wp_register_style(
    'd_boostrap_icon',
    get_theme_file_uri('assets/css/bootstrap/bootstrap.min.css')
  );
  wp_register_style(
    'd_main',
    get_theme_file_uri('assets/css/stylesheet.css')
  );
  wp_register_style(
    'd_overlay-menu',
    get_theme_file_uri('assets/js/overlay-menu/css/style12.css')
  );
  wp_register_style(
    'd_flexslider',
    get_theme_file_uri('assets/css/flexslider/flexslider.css')
  );
  wp_register_style(
    'd_spinkit',
    get_theme_file_uri('assets/css/spinkit/spinkit.css')
  );
  wp_register_style(
    'd_magnific-popup',
    get_theme_file_uri('assets/js/magnific-popup/magnific-popup.css')
  );
  wp_register_style(
    'd_rev_settings',
    get_theme_file_uri('assets/revolution/css/settings.css')
  );
  wp_register_style(
    'd_rev_layers',
    get_theme_file_uri('assets/revolution/css/layers.css')
  );
  wp_register_style(
    'd_rev_nav',
    get_theme_file_uri('assets/revolution/css/navigation.css')
  );
  wp_register_style(
    'd_rev_pe-icon-7',
    get_theme_file_uri('assets/revolution/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css')
  );
  wp_register_style(
    'd_rev_font-awesome',
    get_theme_file_uri('assets/revolution/fonts/font-awesome/css/font-awesome.min.css')
  );
  wp_register_style(
    'd_js-owl-carousel',
    get_theme_file_uri('assets/js/owl-carousel/owl.carousel.css')
  );
  wp_register_style(
    'd_js-owl-theme-default',
    get_theme_file_uri('assets/js/owl-carousel/owl.theme.default.min.css')
  );
  wp_register_style(
    'd_font-line-icons',
    get_theme_file_uri('assets/fonts/simple-line-icons/css/simple-line-icons.css')
  );
  wp_register_style(
    'd_font-awesome',
    get_theme_file_uri('assets/fonts/font-awesome/css/font-awesome.min.css')
  );

  wp_enqueue_style('d_front-rubik_and_pacifico');
  wp_enqueue_style('d_boostrap_icon');
  wp_enqueue_style('d_main');
  wp_enqueue_style('d_overlay-menu');
  wp_enqueue_style('d_flexslider');
  wp_enqueue_style('d_spinkit');
  wp_enqueue_style('d_magnific-popup');
  wp_enqueue_style('d_rev_settings');
  wp_enqueue_style('d_rev_layers');
  wp_enqueue_style('d_rev_nav');
  wp_enqueue_style('d_rev_pe-icon-7');
  wp_enqueue_style('d_rev_font-awesome');
  wp_enqueue_style('d_js-owl-carousel');
  wp_enqueue_style('d_js-owl-theme-default');
  wp_enqueue_style('d_font-line-icons');
  wp_enqueue_style('d_font-awesome');
}